qplot(displ, hwy, data = mpg) +   facet_wrap(class)
library(ggplot2)
qplot(cty, hwy, data = mpg)
qplot(displ, hwy, data = mpg)
qplot(displ, hwy, data = mpg,color=class)
qplot(displ, hwy, data = mpg)
qplot(displ, hwy, data = mpg,color=class)
qplot(displ, hwy, data = mpg) +   facet_grid(. ~ cyl)
qplot(displ, hwy, data = mpg) +   facet_grid(drv ~ .)
qplot(displ, hwy, data = mpg) +   facet_grid(drv ~ cyl)
qplot(displ, hwy, data = mpg) +   facet_wrap(~ class)
(
qplot(displ, hwy, data = mpg) +   facet_grid(drv ~ cyl)
qplot(displ, hwy, data = mpg) +   facet_grid(drv ~ cyl)
qplot(displ, hwy, data = mpg) +   facet_grid(drv ~ cyl)
qplot(displ, hwy, data = mpg) +   facet_wrap(class)
qplot(displ, hwy, data = mpg) +   facet_wrap(~class)
View(mpg)
qplot(displ, hwy, data = mpg) +   facet_wrap(~trans)

qplot(cty, hwy, data = mpg)
qplot(cty, hwy, data = mpg,geom="Jitter")


qplot(class, hwy, data = mpg)
qplot(reorder(class, hwy),hwy, data = mpg,geom="Jitter")
qplot(reorder(class, hwy),hwy, data = mpg,geom="boxplot")
qplot(reorder(class, hwy),hwy, data = mpg,geom=c("Jitter","boxplot"))
qplot(reorder(class, hwy),hwy, data = mpg,geom="Jitter")
